Profile model
dapierrot21/1_week_sprint pull request #2
Opened 2022-02-16 17:40 UTC by dapierrot21

### What this PR does (required):
- This PR creates a profile model that has fields that represents what is needed from the user.

2022-02-18 14:38 UTC, moffatethan requested changes
Let's change the base of this PR to be the `FESignupPage/LoginPage` so we don't see those files being changed in this PR 🙂. 

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

2022-02-18 14:42 UTC, moffatethan requested changes
Nice work on this - just some comments to address on the model then this should be good to go. Thanks Dean!

2022-02-18 14:42 UTC, moffatethan commented on server/models/Profile.js
> +    },
We don't need to specify this field - mongodb automatically assigns unique ids to each item in a collection. This can be removed

2022-02-18 14:42 UTC, moffatethan commented on server/models/Profile.js
> +    firstname: {
`firstName` let's use camelCase. Change throughout the model please 🙂

2022-02-18 14:42 UTC, moffatethan commented on server/models/Profile.js
> +    },
Let's do an enum here 

['Male', 'Female', 'Other']

2022-02-18 14:42 UTC, moffatethan commented on server/models/Profile.js
> +    },
Let's make this type a `Date` rather than String. It's important we use the proper types for each property otherwise we aren't being very efficient with our data in the back-end.

2022-02-18 14:42 UTC, moffatethan commented on server/models/Profile.js
> +    },
The user component has the email address for authentication, we don't need to store this twice.

2022-02-18 14:42 UTC, moffatethan commented on server/models/Profile.js
> +    },
Would be nice to add some validation to ensure it's a legit phone number coming in via regular expression

2022-02-18 14:42 UTC, moffatethan commented on server/models/Profile.js
> +    }
We can remove this - hours/days is not going to work out for availability. Will discuss more about this with you when the time comes

2022-02-21 19:01 UTC, dapierrot21 commented
I change the base to the correct branch and removed the fields that needed to be remove. Also correct data types and included a reference to the user model. camelCase the fields as well and added regex validations to the phone number field.

2022-02-21 19:22 UTC, merged