Profile controller
dapierrot21/1_week_sprint pull request #3
Opened 2022-02-21 19:46 UTC by dapierrot21

### What this PR does (required):
- This PR is a controller function with basic CRUD functions. The controller has direct access to modify instances of the model and create instances as well.

- createProfile - Creates
- deleteUserProfile - Deletes
- updateProfile - Updates
- getUserProfileById - Get By Id
- getProfiles - Get all profiles

2022-03-04 17:11 UTC, moffatethan requested changes

2022-03-04 17:11 UTC, moffatethan commented on client/src/components/AuthHeader/AuthHeader.tsx
> +  // eslint-disable-next-line
Probably should avoid this and use the proper event type 🙂

2022-03-04 17:11 UTC, moffatethan commented on server/controllers/profile.js
> +    }
This would be better suited in the middleware validation. Take a look at our validation file in the server directory.

2022-03-04 17:11 UTC, moffatethan commented on server/controllers/profile.js
> +        });
Don't really want to maintain this, could we do `...req.body`?

2022-03-04 17:11 UTC, moffatethan commented on server/controllers/profile.js
> +        //return the respond deconstructed
Let's remove these comments cause the code is describing itself.

2022-03-04 17:11 UTC, moffatethan commented on server/controllers/profile.js
> +        profile.payment = req.body.payment,
Couldn't this technically set the firstName to undefined if it's not passed in?

2022-03-04 17:11 UTC, moffatethan commented on server/controllers/profile.js
> +        }
Using express validation middleware we can avoid this try/catch.

2022-03-04 17:11 UTC, moffatethan commented on server/controllers/profile.js
> +    }
Same here 👍🏻

2022-03-04 17:11 UTC, moffatethan commented on server/models/Profile.js
> +        type: Array,
Maybe an enum is better? I don't think people will define multiple genders.

2022-03-04 17:11 UTC, moffatethan commented on server/routes/profile.js
> +router.route("/create-profile").post(createProfile);
This route can just be `/` because it's a POST request it means we are creating a resource, in this case a profile since the prefix route is `/profile`

2022-03-04 18:51 UTC, dapierrot21 commented on server/controllers/profile.js
> +        //return the respond deconstructed
Removed

2022-03-04 19:00 UTC, dapierrot21 commented on server/controllers/profile.js
> +        });
Used .create() to removed then need for profile.save().

2022-03-04 19:11 UTC, dapierrot21 commented on server/routes/profile.js
> +router.route("/create-profile").post(createProfile);
Done! and also added validate function for the request fields.

2022-03-04 19:27 UTC, dapierrot21 commented on server/controllers/profile.js
> +    }
Removed and added to the middleware validation.

2022-03-04 19:51 UTC, dapierrot21 commented on server/controllers/profile.js
> +        profile.payment = req.body.payment,
Would I need to check if all fields were entered and if not send a response to enter it?

2022-03-14 18:06 UTC, moffatethan commented on server/controllers/profile.js
> +        profile.payment = req.body.payment,
Rather we should just default to the current name of the profile if the firstName isn't passed through the body so no issues arise with the data being lost.

2022-03-14 18:07 UTC, moffatethan commented on server/routes/profile.js
> +router.route("/create-profile").post(createProfile);
I don't see any commit updated? Did you push up these changes?

2022-03-14 21:39 UTC, dapierrot21 commented on server/routes/profile.js
> +router.route("/create-profile").post(createProfile);
Sorry I was waiting on your response before I pushed anything, but code changes are pushed now.

2022-03-18 19:22 UTC, moffatethan approved these changes

2022-03-18 21:15 UTC, merged