Fe dashboard
dapierrot21/1_week_sprint pull request #4
Opened 2022-02-24 19:10 UTC by dapierrot21

### What this PR does (required):
-Adapted the current project skeleton to match project mockups

### Screenshots / Videos (front-end only):
<img width="1440" alt="Dashboard FE Mobile" src="https://user-images.githubusercontent.com/25135432/155590856-0233d8df-2c6f-4f60-bac9-e06612a868a3.png">
 <img width="1440" alt="DashboardFE" src="https://user-images.githubusercontent.com/25135432/155590841-e2c854ee-4da1-4d10-bb26-6eadc32f258c.png">

2022-03-04 17:07 UTC, moffatethan requested changes

2022-03-04 17:07 UTC, moffatethan commented on client/src/components/Navbar/Navbar.tsx
> +          {/* <IconButton size="large" edge="start" color="inherit" aria-label="menu" sx={{ mr: 2 }}>
Let's remove the commented code 🙂

2022-03-04 18:32 UTC, dapierrot21 commented on client/src/components/Navbar/Navbar.tsx
> +          {/* <IconButton size="large" edge="start" color="inherit" aria-label="menu" sx={{ mr: 2 }}>
Removed

2022-03-14 18:08 UTC, moffatethan approved these changes

2022-03-14 21:37 UTC, merged